server:
  port: 8090

spring:
  redis:
    database: 0
    host: www.colinting.ltd
    port: 6379
    password:
    timeout: 10000
    jedis-pool:
      max-active: 1024
      max-wait-millis: 10000
      max-idle: 200
      min-idle: 0

